#!/usr/bin/env bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" <<EOSQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${SUPERSET_DB_USER}') THEN
    CREATE ROLE ${SUPERSET_DB_USER} LOGIN PASSWORD '${SUPERSET_DB_PASSWORD}';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${AIRFLOW_DB_USER}') THEN
    CREATE ROLE ${AIRFLOW_DB_USER} LOGIN PASSWORD '${AIRFLOW_DB_PASSWORD}';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${WAREHOUSE_DB_USER}') THEN
    CREATE ROLE ${WAREHOUSE_DB_USER} LOGIN PASSWORD '${WAREHOUSE_DB_PASSWORD}';
  END IF;
END
\$\$;

SELECT 'CREATE DATABASE ${SUPERSET_DB_NAME} OWNER ${SUPERSET_DB_USER}'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${SUPERSET_DB_NAME}')
\\gexec

SELECT 'CREATE DATABASE ${AIRFLOW_DB_NAME} OWNER ${AIRFLOW_DB_USER}'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${AIRFLOW_DB_NAME}')
\\gexec

SELECT 'CREATE DATABASE ${WAREHOUSE_DB_NAME} OWNER ${WAREHOUSE_DB_USER}'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${WAREHOUSE_DB_NAME}')
\\gexec
EOSQL
